import { db } from './db';
import { Trade, Note, PerformanceGoal, MarketType } from '../types';

export async function seedDemoData(userId: string): Promise<void> {
  // Clear existing trades, notes, goals for this user to prevent cluttering
  await db.transaction('rw', [db.trades, db.notes, db.goals], async () => {
    await db.trades.where('userId').equals(userId).delete();
    await db.notes.where('userId').equals(userId).delete();
    await db.goals.where('userId').equals(userId).delete();
  });

  const now = new Date();
  
  // Helpers to get dates in past
  const getPastDateStr = (daysAgo: number): string => {
    const d = new Date();
    d.setDate(now.getDate() - daysAgo);
    return d.toISOString().split('T')[0];
  };

  const demoTrades: Omit<Trade, 'tradeNumber' | 'createdAt'>[] = [
    {
      userId,
      date: getPastDateStr(14),
      time: '10:30',
      market: 'Crypto',
      exchange: 'Binance',
      assetName: 'Bitcoin',
      symbol: 'BTCUSDT',
      type: 'BUY',
      direction: 'LONG',
      strategyUsed: 'Order Block / FVG',
      setupName: 'H4 Bullish FVG Retest',
      timeframe: '4h',
      entryPrice: 58200,
      stopLoss: 57400,
      takeProfit: 60200,
      exitPrice: 60200,
      quantity: 0.25,
      riskPercent: 1.5,
      rewardRatio: 2.5,
      positionSize: 14550,
      fees: 14.55,
      pnl: 485.45,
      pnlPercent: 3.34,
      status: 'WIN',
      emotionBefore: 'Calm',
      emotionAfter: 'Satisfied',
      confidence: 8,
      mistakes: ['None'],
      lessonsLearned: 'Patience paid off. Held through minor drawdowns on the 1h chart as the H4 HTF structure was strongly bullish.',
      notes: 'Logged entry at the exact 50% equilibrium mark of the FVG. Stop loss placed below the swing low.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: true,
      },
      isFavorite: true,
      isPinned: false,
      tags: ['Crypto', 'OB', 'FVG'],
      comments: [
        {
          id: 'c1',
          author: 'System Reviewer',
          text: 'Perfect execution. Stop loss was set correctly at the swing structural invalidation point.',
          date: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        }
      ]
    },
    {
      userId,
      date: getPastDateStr(12),
      time: '14:15',
      market: 'Forex',
      exchange: 'Oanda',
      assetName: 'Euro / US Dollar',
      symbol: 'EURUSD',
      type: 'SELL',
      direction: 'SHORT',
      strategyUsed: 'Liquidity Grab',
      setupName: 'London Session High Sweep',
      timeframe: '15m',
      entryPrice: 1.0920,
      stopLoss: 1.0945,
      takeProfit: 1.0850,
      exitPrice: 1.0945,
      quantity: 100000,
      riskPercent: 1.0,
      rewardRatio: 2.8,
      positionSize: 109200,
      fees: 8.0,
      pnl: -258.0,
      pnlPercent: -0.24,
      status: 'LOSS',
      emotionBefore: 'Anxious',
      emotionAfter: 'Anger',
      confidence: 6,
      mistakes: ['FOMO Entry', 'Overleveraged'],
      lessonsLearned: 'Rushed the entry before the 15m candle actually closed. The market swept the high but closed back below, then squeezed higher before dropping.',
      notes: 'Market was in a strong uptrend today. Attempting to catch counter-trend reversals in London session is dangerous without clean structural shifts.',
      images: [],
      checklist: {
        trendConfirmed: false,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: false,
        newsChecked: true,
        followedStrategy: false,
      },
      isFavorite: false,
      isPinned: false,
      tags: ['Forex', 'Liquidity', 'Loss'],
    },
    {
      userId,
      date: getPastDateStr(10),
      time: '09:45',
      market: 'Stocks',
      exchange: 'NYSE',
      assetName: 'Apple Inc.',
      symbol: 'AAPL',
      type: 'BUY',
      direction: 'LONG',
      strategyUsed: 'Moving Average Crossover',
      setupName: '9/21 EMA Golden Cross',
      timeframe: '1h',
      entryPrice: 185.50,
      stopLoss: 183.00,
      takeProfit: 191.00,
      exitPrice: 191.00,
      quantity: 100,
      riskPercent: 2.0,
      rewardRatio: 2.2,
      positionSize: 18550,
      fees: 5.00,
      pnl: 545.00,
      pnlPercent: 2.94,
      status: 'WIN',
      emotionBefore: 'Focused',
      emotionAfter: 'Relieved',
      confidence: 7,
      mistakes: ['None'],
      lessonsLearned: 'EMA crossovers work beautifully in strong trending markets. Check daily index context before buying individual equities.',
      notes: 'SPY was rallying today which provided strong market tailwinds for tech names.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: true,
      },
      isFavorite: false,
      isPinned: false,
      tags: ['Stocks', 'EMA', 'AAPL'],
    },
    {
      userId,
      date: getPastDateStr(8),
      time: '16:00',
      market: 'Crypto',
      exchange: 'Binance',
      assetName: 'Ethereum',
      symbol: 'ETHUSDT',
      type: 'SELL',
      direction: 'SHORT',
      strategyUsed: 'Support & Resistance',
      setupName: 'Resistance Rejection',
      timeframe: '1h',
      entryPrice: 3450,
      stopLoss: 3510,
      takeProfit: 3250,
      exitPrice: 3450,
      quantity: 4.0,
      riskPercent: 1.0,
      rewardRatio: 3.3,
      positionSize: 13800,
      fees: 13.80,
      pnl: -13.80,
      pnlPercent: -0.10,
      status: 'BREAKEVEN',
      emotionBefore: 'Calm',
      emotionAfter: 'Relieved',
      confidence: 7,
      mistakes: ['None'],
      lessonsLearned: 'Smart move protecting capital. Once price moved 1.5R into profit, stop loss was adjusted to entry (breakeven). It turned around and stopped me out before tanking further.',
      notes: 'Price reached $3360 before bouncing hard back to the entry price.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: true,
      },
      isFavorite: false,
      isPinned: false,
      tags: ['Crypto', 'SR', 'Breakeven'],
    },
    {
      userId,
      date: getPastDateStr(7),
      time: '11:00',
      market: 'Stocks',
      exchange: 'NASDAQ',
      assetName: 'Tesla Motors',
      symbol: 'TSLA',
      type: 'BUY',
      direction: 'LONG',
      strategyUsed: 'Gap Fill',
      setupName: 'Morning Gap and Go',
      timeframe: '5m',
      entryPrice: 220.00,
      stopLoss: 216.50,
      takeProfit: 228.00,
      exitPrice: 216.50,
      quantity: 50,
      riskPercent: 1.5,
      rewardRatio: 2.3,
      positionSize: 11000,
      fees: 4.50,
      pnl: -179.50,
      pnlPercent: -1.63,
      status: 'LOSS',
      emotionBefore: 'Greedy',
      emotionAfter: 'Regretful',
      confidence: 5,
      mistakes: ['Chased Market', 'FOMO Entry'],
      lessonsLearned: 'Do not chase high momentum gaps at the open. Wait for the initial 15-minute range to establish, then check the pullback levels.',
      notes: 'TSLA opened high and immediately pulled back, hitting my stop loss within 8 minutes of opening bell.',
      images: [],
      checklist: {
        trendConfirmed: false,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: false,
        followedStrategy: false,
      },
      isFavorite: false,
      isPinned: false,
      tags: ['Stocks', 'GapFill', 'Loss'],
    },
    {
      userId,
      date: getPastDateStr(5),
      time: '08:00',
      market: 'Futures',
      exchange: 'CME',
      assetName: 'E-mini S&P 500',
      symbol: 'ES1!',
      type: 'BUY',
      direction: 'LONG',
      strategyUsed: 'Order Block / FVG',
      setupName: 'Daily OB Retest',
      timeframe: '15m',
      entryPrice: 5350.00,
      stopLoss: 5330.00,
      takeProfit: 5410.00,
      exitPrice: 5410.00,
      quantity: 2,
      riskPercent: 2.0,
      rewardRatio: 3.0,
      positionSize: 10700,
      fees: 10.0,
      pnl: 590.0,
      pnlPercent: 5.51,
      status: 'WIN',
      emotionBefore: 'Focused',
      emotionAfter: 'Satisfied',
      confidence: 9,
      mistakes: ['None'],
      lessonsLearned: 'Trading with structural bias yields the highest win rates. The daily trend was bullish and the retracement was clean.',
      notes: 'Filled my limit order at the start of New York pre-market. Took full profit at target.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: true,
      },
      isFavorite: true,
      isPinned: true,
      tags: ['Futures', 'S&P', 'OB', 'Win'],
    },
    {
      userId,
      date: getPastDateStr(4),
      time: '13:00',
      market: 'Forex',
      exchange: 'Oanda',
      assetName: 'Gold Spot',
      symbol: 'XAUUSD',
      type: 'BUY',
      direction: 'LONG',
      strategyUsed: 'Liquidity Grab',
      setupName: 'Asia Low Sweep',
      timeframe: '30m',
      entryPrice: 2310.00,
      stopLoss: 2298.00,
      takeProfit: 2340.00,
      exitPrice: 2340.00,
      quantity: 50, // Ounces
      riskPercent: 2.0,
      rewardRatio: 2.5,
      positionSize: 115500,
      fees: 15.00,
      pnl: 1485.00,
      pnlPercent: 1.29,
      status: 'WIN',
      emotionBefore: 'Calm',
      emotionAfter: 'Satisfied',
      confidence: 8,
      mistakes: ['None'],
      lessonsLearned: 'Asian session lows are often swept during London/NY overlap. Gold is highly volatile; wider stop losses are necessary to avoid premature stop outs.',
      notes: 'Entry was triggered right after the US CPI news sweep. Gold surged $30 in 2 hours.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: true,
      },
      isFavorite: true,
      isPinned: false,
      tags: ['Forex', 'Gold', 'Sweep', 'Win'],
    },
    {
      userId,
      date: getPastDateStr(3),
      time: '15:30',
      market: 'Crypto',
      exchange: 'Coinbase',
      assetName: 'Solana',
      symbol: 'SOLUSDT',
      type: 'BUY',
      direction: 'LONG',
      strategyUsed: 'Breakout',
      setupName: 'Bull Flag Breakout',
      timeframe: '15m',
      entryPrice: 142.00,
      stopLoss: 138.50,
      takeProfit: 151.00,
      exitPrice: 138.50,
      quantity: 80,
      riskPercent: 1.0,
      rewardRatio: 2.57,
      positionSize: 11360,
      fees: 11.36,
      pnl: -291.36,
      pnlPercent: -2.56,
      status: 'LOSS',
      emotionBefore: 'Greedy',
      emotionAfter: 'Anxious',
      confidence: 6,
      mistakes: ['FOMO Entry', 'Moved Stop Loss'],
      lessonsLearned: 'I moved the stop loss closer during the trade to minimize losses, which got me stopped out on a minor wick before the flag broke out. Follow initial system rules!',
      notes: 'Flag broke out to $150 shortly after stopping me out. Extremely frustrating but shows why we must leave stop losses alone.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: false,
      },
      isFavorite: false,
      isPinned: false,
      tags: ['Crypto', 'Solana', 'Loss'],
    },
    {
      userId,
      date: getPastDateStr(2),
      time: '09:00',
      market: 'Crypto',
      exchange: 'Binance',
      assetName: 'Bitcoin',
      symbol: 'BTCUSDT',
      type: 'SELL',
      direction: 'SHORT',
      strategyUsed: 'Order Block / FVG',
      setupName: 'H1 Bearish FVG Retest',
      timeframe: '1h',
      entryPrice: 62400,
      stopLoss: 63100,
      takeProfit: 60500,
      exitPrice: 60500,
      quantity: 0.35,
      riskPercent: 1.5,
      rewardRatio: 2.7,
      positionSize: 21840,
      fees: 21.84,
      pnl: 643.16,
      pnlPercent: 2.95,
      status: 'WIN',
      emotionBefore: 'Focused',
      emotionAfter: 'Satisfied',
      confidence: 8,
      mistakes: ['None'],
      lessonsLearned: 'Sticking to HTF bearish bias was key. Bitcoin was exhibiting heavy distribution behavior near local resistance.',
      notes: 'NY session opened with strong selling pressure, driving price straight to the H1 demand block.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: true,
      },
      isFavorite: false,
      isPinned: false,
      tags: ['Crypto', 'BTC', 'Short', 'Win'],
    },
    {
      userId,
      date: getPastDateStr(1),
      time: '14:30',
      market: 'Stocks',
      exchange: 'NASDAQ',
      assetName: 'Nvidia Corp.',
      symbol: 'NVDA',
      type: 'BUY',
      direction: 'LONG',
      strategyUsed: 'Moving Average Crossover',
      setupName: '9/21 EMA Cross on H1',
      timeframe: '1h',
      entryPrice: 122.00,
      stopLoss: 119.50,
      takeProfit: 128.00,
      exitPrice: 120.50,
      quantity: 120,
      riskPercent: 1.0,
      rewardRatio: 2.4,
      positionSize: 14640,
      fees: 6.00,
      pnl: -186.00,
      pnlPercent: -1.27,
      status: 'LOSS',
      emotionBefore: 'Anxious',
      emotionAfter: 'Calm',
      confidence: 6,
      mistakes: ['Early Exit'],
      lessonsLearned: 'Exited manually before stop loss hit because I was scared of a deeper correction. The market rebounded right after I closed my position.',
      notes: 'Closed position manually at $120.50. Low confidence and lack of emotional detachment.',
      images: [],
      checklist: {
        trendConfirmed: true,
        riskCalculated: true,
        stopLossPlaced: true,
        targetIdentified: true,
        positionSizeCorrect: true,
        newsChecked: true,
        followedStrategy: true,
      },
      isFavorite: false,
      isPinned: false,
      tags: ['Stocks', 'NVDA', 'Loss'],
    }
  ];

  // Insert Trades
  for (const t of demoTrades) {
    const nextNum = await db.trades.where('userId').equals(userId).count() + 1;
    const tradeId = crypto.randomUUID();
    await db.trades.add({
      ...t,
      id: tradeId,
      tradeNumber: nextNum,
      createdAt: new Date(new Date(t.date + 'T' + t.time).getTime()).toISOString()
    } as Trade);
  }

  // Seed Goals
  const currentMonth = now.toISOString().substring(0, 7); // YYYY-MM
  const demoGoal: PerformanceGoal = {
    id: crypto.randomUUID(),
    userId,
    monthlyProfitTarget: 1500,
    maxDailyLoss: 400,
    weeklyWinRateTarget: 55,
    tradeCountTarget: 12,
    period: currentMonth,
    createdAt: now.toISOString()
  };
  await db.goals.put(demoGoal);

  // Seed Notes
  const demoNotes: Note[] = [
    {
      id: crypto.randomUUID(),
      userId,
      title: 'Daily Market Pre-plan - July 2026',
      type: 'DAILY',
      content: `<h2>Daily Prep Outline</h2><ul><li>Check DXY bias - Daily chart is consolidating, likely to bounce from structural support.</li><li>EURUSD looks prime for a short once the London session swept liquidity.</li><li>Bitcoin consolidating between $60k and $63k. Ready to take short orders on resistance rejections.</li></ul><p><strong>Rules:</strong> Max 2 trades today. No chasing wicks.</p>`,
      date: getPastDateStr(2),
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      userId,
      title: 'Weekly Performance Review - Week 26',
      type: 'WEEKLY',
      content: `<h2>Weekly Analysis</h2><p>Excellent week in terms of process. Made 5 trades, 3 wins, 2 losses. Total profit was $850. Win rate 60%.</p><p><strong>Psychology:</strong> Very calm. The position size calculator helped reduce anxiety because I knew my risk in dollars beforehand.</p><p><strong>Mistakes to Avoid:</strong> Solved the FOMO issue but still need to improve stop loss adjustments. Do not move stops closer during active candles.</p>`,
      date: getPastDateStr(1),
      createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    }
  ];

  for (const note of demoNotes) {
    await db.notes.put(note);
  }
}
